name: Deploy SvelteKit

on:
  push:
    branches: ['main']

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Upgrade ke v20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: |
          npm run build
          # Pastikan tidak ada subfolder yang mengganggu
          mv build/app/* build/ 2>/dev/null || true
          touch build/.nojekyll
          
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2